---
title: "Modularity math 76"
author: "Anna Vasenina"
date: "2023-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(igraph)
library(igraphdata) 
data("karate")
```

We now run community detection varying the resolution parameter.

```{r}
gamma <- seq(0.2,4,0.04)
nc <- vector("numeric",length(gamma))
for (i in 1:length(gamma)){
  gc <- cluster_leiden(karate, objective_function = "modularity",
                       n_iterations = 4, resolution_parameter = gamma[i])
  nc[i] <- length(gc)
}
plot(gamma,nc,xlab="gamma",ylab="# Communities",main="Karate Club")
```

```{r}
kc05 <- cluster_leiden(karate, objective_function = "modularity",
                       n_iterations = 3, resolution_parameter = 0.5)
kc10 <- cluster_leiden(karate, objective_function = "modularity",
                       n_iterations = 3, resolution_parameter = 1.0)
table(membership(kc05),membership(kc10))
```

```{r}
kc_two <- cluster_leiden(karate, objective_function = "modularity",
                       n_iterations = 3, resolution_parameter = 0.5)
plot(kc_two, karate)
```




```{r}
data(enron)
enron <- as.undirected(enron,mode="each")
summary(enron)
```

We now run community detection varying the resolution parameter.

```{r}
gamma <- seq(0.2,4,0.04)
nc <- vector("numeric",length(gamma))
for (i in 1:length(gamma)){
  gc <- cluster_leiden(enron, objective_function = "modularity",
                       n_iterations = 3, resolution_parameter = gamma[i])
  nc[i] <- length(gc)
}
plot(gamma,nc,xlab="gamma",ylab="# Communities",main="Enron Email")
```

Let's contrast results at gamma=2.2 and 3.2: the above results for small self-loop weights with those near the value 100:

```{r}
ec22 <- cluster_leiden(enron, objective_function = "modularity",
                       n_iterations = 3, resolution_parameter = 2.2)
ec32 <- cluster_leiden(enron, objective_function = "modularity",
                       n_iterations = 3, resolution_parameter = 3.2)
table(membership(ec22),membership(ec32))
```
